name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # packages
  cupertino_icons: ^1.0.2
  dart_twitter_api: ^0.5.3
  equatable: ^2.0.0
  flare_flutter: ^3.0.0
  flutter_bloc: ^7.0.0
  flutter_colorpicker: ^0.4.0
  flutter_feather_icons: ^2.0.0+1
  flutter_material_color_picker: ^1.0.5 # non null safe
  flutter_staggered_grid_view: ^0.4.0
  get_it: ^6.1.1
  humanize: ^0.3.0 # non null safe
  intl: ^0.17.0
  like_button: ^2.0.2
  logging: ^1.0.1
  mime_type: ^1.0.0
  photo_view:
    # custom photo_view with better gesture recognition
    git: git://github.com/robertodoering/photo_view.git
  provider: ^5.0.0
  scroll_to_index: ^2.0.0
  timeago: ^3.0.2
  visibility_detector: ^0.2.0

  # plugins
  connectivity: ^3.0.3
  device_info: ^2.0.0
  downloads_path_provider: ^0.1.0 # non null safe
  file_picker: ^3.0.1
  firebase_analytics: ^8.0.0
  flutter_displaymode: ^0.3.1-nullsafety.0
  flutter_downloader: ^1.6.0
  flutter_ffmpeg: ^0.4.0
  flutter_twitter_login: # non null safe
    git: git://github.com/robertodoering/flutter_twitter_login.git
  keyboard_visibility: ^0.5.6 # non null safe
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.3
  sentry_flutter: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  video_player: ^2.1.1
  webview_flutter: ^2.0.4

dev_dependencies:
  bloc_test: ^8.0.0
  build_runner: ^1.11.5 # upgrade after null safety migration
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1 # upgrade after null safety migration
  mockito: ^4.1.3

dependency_overrides:
  json_annotation: '>=3.1.0 <3.2.0' # remove after upgrading json_serializable

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - android/fastlane/metadata/android/free/en-US/changelogs/

  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700

  - family: NotoSans
    # used as a fallback font
    # covers a lot of scripts and obscure unicode characters
    # https://fonts.google.com/specimen/Noto+Sans
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf
      - asset: assets/fonts/NotoSans-Bold.ttf
        weight: 700
